// `pnpm openapi`: writes docs/api/openapi.json from the api app's Zod routes and regenerates the
// typed client types in packages/contracts. `--check` fails when the committed files are stale.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { format, resolveConfig } from 'prettier';
import { SkeletonActorResolver } from '../supabase/functions/_shared/actor.ts';
import { createApp, OPENAPI_INFO } from '../supabase/functions/api/app.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const jsonPath = resolve(root, 'docs/api/openapi.json');
const typesPath = resolve(root, 'packages/contracts/src/generated/openapi.ts');
const check = process.argv.includes('--check');

const app = createApp({
  version: 'openapi',
  allowedOrigins: [],
  actors: new SkeletonActorResolver('unused'),
  probes: {
    db: async () => {},
    storage: async () => {},
    queue: async () => {},
    aiKeyPresent: false,
  },
});

const document = app.getOpenAPI31Document(OPENAPI_INFO);
const json = `${JSON.stringify(document, null, 2)}\n`;
const ast = await openapiTS(JSON.parse(json) as Parameters<typeof openapiTS>[0]);
const banner = '// Generated by `pnpm openapi` from docs/api/openapi.json. Do not edit.\n';
const types = await format(banner + astToString(ast), {
  ...(await resolveConfig(typesPath)),
  parser: 'typescript',
});

const outputs: [string, string][] = [
  [jsonPath, json],
  [typesPath, types],
];

if (check) {
  const stale: string[] = [];
  for (const [path, content] of outputs) {
    const current = await readFile(path, 'utf8').catch(() => '');
    if (current !== content) stale.push(path.replace(`${root}/`, ''));
  }
  if (stale.length > 0) {
    console.error(`OpenAPI output is stale: ${stale.join(', ')}. Run \`pnpm openapi\` and commit.`);
    process.exit(1);
  }
  console.log('OpenAPI document and client types are up to date.');
} else {
  for (const [path, content] of outputs) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
    console.log(`wrote ${path.replace(`${root}/`, '')}`);
  }
}
